language: java
sudo: false

jdk:
  - openjdk8
  - openjdk11

env:
  - TESTFOLDER=jraft-core
  - TESTFOLDER=jraft-rheakv/rheakv-core
  - TESTFOLDER=jraft-rheakv/rheakv-pd
  - TESTFOLDER=jraft-extension/rpc-grpc-impl

cache:
  directories:
  - $HOME/.m2

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - sh ./tools/check_format.sh
script:
  - MAVEN_SKIP_RC=true MAVEN_OPTS="-Xmx1g -server -XX:+UseG1GC" travis_retry mvn --projects $TESTFOLDER test
