name: build-macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Check format
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && sh ./tools/check_format.sh

  test_jraft_core:
    needs: check_format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-core test
            || mvn --projects jraft-core test
            || mvn --projects jraft-core test)

  test_rheakv_core:
    needs: check_format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-rheakv/rheakv-core test
            || mvn --projects jraft-rheakv/rheakv-core test
            || mvn --projects jraft-rheakv/rheakv-core test)

  test_rheakv_pd:
    needs: check_format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-rheakv/rheakv-pd test
            || mvn --projects jraft-rheakv/rheakv-pd test
            || mvn --projects jraft-rheakv/rheakv-pd test)

  test_rpc_grpc_impl:
    needs: check_format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-extension/rpc-grpc-impl test
            || mvn --projects jraft-extension/rpc-grpc-impl test
            || mvn --projects jraft-extension/rpc-grpc-impl test)
            
  test_leveldb_log_storage_impl:
    needs: check_format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-extension/leveldb-log-storage-impl test
            || mvn --projects jraft-extension/leveldb-log-storage-impl test
            || mvn --projects jraft-extension/leveldb-log-storage-impl test)

  test_h2mvstore_log_storage_impl:
    needs: check_format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-extension/h2mvstore-log-storage-impl test
            || mvn --projects jraft-extension/h2mvstore-log-storage-impl test
            || mvn --projects jraft-extension/h2mvstore-log-storage-impl test)

  test_mapdb_log_storage_impl:
    needs: check_format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-extension/mapdb-log-storage-impl test
            || mvn --projects jraft-extension/mapdb-log-storage-impl test
            || mvn --projects jraft-extension/mapdb-log-storage-impl test)

  test_chroniclemap_log_storage_impl:
    needs: check_format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-extension/chronicle-map-log-storage-impl test
            || mvn --projects jraft-extension/chronicle-map-log-storage-impl test
            || mvn --projects jraft-extension/chronicle-map-log-storage-impl test)

  test_bdb_log_storage_impl:
    needs: check_format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-extension/bdb-log-storage-impl test
            || mvn --projects jraft-extension/bdb-log-storage-impl test
            || mvn --projects jraft-extension/bdb-log-storage-impl test)
